// Import styling
import "./globals.css";

// Import components
import Header from "@/components/header";
import Footer from "@/components/footer";

// Create 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-cream">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
